In [1]:
%load_ext autoreload
%autoreload 2
import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
import scipy
from scripts.utils import *
from scripts.gaussianclass import *

In [2]:
D,L,classes,features=init_dataset()

Le classi sono : ['setosa' 'versicolor' 'virginica'] e le features :['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [3]:
(DTR, LTR), (DVAL, LVAL) = split_db_2to1(D, L)

## Classificatore Gaussiano Multivariato

Il primo modello che implementiamo è il Classificatore Gaussiano Multivariato (MVG). Come abbiamo visto, il classificatore assume che i campioni di ogni classe c ∈ {0, 1, 2} possono essere modellati come campioni di una distribuzione gaussiana multivariata con media e matrici di covarianza dipendenti dalla classe:

$$f_{X|C}(x|c) = \mathcal{N}(x|\mu_c, \Sigma_c)$$

La soluzione ML per i parametri è data dalla media empirica e dalla matrice di covarianza di ogni classe:

$$\mu_c^* = \frac{1}{N_c} \sum_i x_{c,i}, \quad \Sigma_c^* = \frac{1}{N_c} \sum_i (x_{c,i} - \mu_c^*)(x_{c,i} - \mu_c^*)^T$$

dove $x_{c,i}$ è l'i-esimo campione della classe c.

In [4]:
LTR==1

array([False,  True, False, False, False, False, False,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
       False, False, False,  True, False, False, False, False, False,
        True,  True, False, False,  True, False, False, False,  True,
       False,  True,  True,  True, False, False, False, False, False,
        True, False, False, False, False,  True, False,  True,  True,
       False, False, False, False,  True, False,  True, False, False,
        True,  True,  True,  True, False, False, False, False,  True,
       False, False,  True, False, False,  True, False,  True, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [5]:
params=get_params_MVG(DTR,LTR)
params

[(array([4.96129032, 3.42903226, 1.46451613, 0.2483871 ]),
  array([[0.13140479, 0.11370447, 0.02862643, 0.01187305],
         [0.11370447, 0.16270552, 0.01844953, 0.01117586],
         [0.02862643, 0.01844953, 0.03583767, 0.00526535],
         [0.01187305, 0.01117586, 0.00526535, 0.0108845 ]])),
 (array([5.91212121, 2.78484848, 4.27272727, 1.33939394]),
  array([[0.26470156, 0.09169881, 0.18366391, 0.05134068],
         [0.09169881, 0.10613407, 0.08898072, 0.04211203],
         [0.18366391, 0.08898072, 0.21955923, 0.06289256],
         [0.05134068, 0.04211203, 0.06289256, 0.03208448]])),
 (array([6.45555556, 2.92777778, 5.41944444, 1.98888889]),
  array([[0.30080247, 0.08262346, 0.18614198, 0.04311728],
         [0.08262346, 0.08533951, 0.06279321, 0.05114198],
         [0.18614198, 0.06279321, 0.18434414, 0.04188272],
         [0.04311728, 0.05114198, 0.04188272, 0.0804321 ]]))]

In [6]:
params[0]

(array([4.96129032, 3.42903226, 1.46451613, 0.2483871 ]),
 array([[0.13140479, 0.11370447, 0.02862643, 0.01187305],
        [0.11370447, 0.16270552, 0.01844953, 0.01117586],
        [0.02862643, 0.01844953, 0.03583767, 0.00526535],
        [0.01187305, 0.01117586, 0.00526535, 0.0108845 ]]))

In [7]:
S=getS(params,DVAL)
S

array([[ 1.55967572e+00,  1.14017174e+00, -1.40657517e+02,
        -4.17161807e+02, -4.79793093e+02,  2.41007437e+00,
         2.10494245e+00,  1.67400801e+00, -1.70961371e+02,
        -1.66665979e+02,  7.06271117e-01, -9.73464551e-01,
        -1.51986858e+02, -2.45521190e-01, -5.63754861e+02,
        -7.67214078e+01, -4.20761218e+02, -1.65272890e+02,
        -7.85138635e-01, -2.42586918e+02, -4.06216307e+00,
        -4.88360403e+02,  2.17363495e+00,  1.81394319e+00,
        -3.95752259e+02,  2.37180771e+00, -4.04665187e+02,
        -1.38807386e+02, -1.18431556e+02, -8.29839492e+01,
        -3.56324460e+02, -3.48262925e+02, -2.27427204e+02,
        -2.46143837e+02,  8.75894828e-01, -9.77609722e+01,
        -4.03297575e+02, -2.91264978e+02,  2.38446728e+00,
        -1.76880387e+02, -1.37384611e+02, -2.41764742e+02,
        -1.73726267e+02, -1.47937484e+00,  1.59429843e+00,
         1.15000214e+00, -3.23352247e+02, -1.20234441e+02,
        -4.86995891e+02,  2.22922516e+00],
       [-5.23

In [8]:
Sjoint=getSJoint(params,DVAL,1/3)
Sjoint

array([[1.58575943e+000, 1.04243514e+000, 2.72957564e-062,
        2.24806026e-182, 1.41705326e-209, 3.71159641e+000,
        2.73554357e+000, 1.77783391e+000, 1.88494475e-075,
        1.38281331e-073, 6.75473622e-001, 1.25923986e-001,
        3.27963237e-067, 2.60765569e-001, 4.86691243e-246,
        1.59659471e-034, 6.14615463e-184, 5.56896774e-073,
        1.52018824e-001, 1.47475180e-106, 5.73724955e-003,
        2.69557088e-213, 2.93005929e+000, 2.04486323e+000,
        4.46535964e-173, 3.57224919e+000, 6.01202795e-177,
        1.73618815e-061, 1.22661255e-052, 3.04373991e-037,
        5.93105804e-156, 1.88023605e-152, 5.65586443e-100,
        4.20695998e-108, 8.00340945e-001, 1.16366505e-043,
        2.36030153e-176, 1.06685624e-127, 3.61775980e+000,
        5.06643905e-078, 7.20278540e-061, 3.35571731e-106,
        1.18718880e-076, 7.59266808e-002, 1.64162425e+000,
        1.05273322e+000, 1.23817483e-141, 2.02173642e-053,
        1.05499498e-212, 3.09755432e+000],
       [6.086

In [9]:
Sjoint.shape

(3, 50)

In [10]:
#Per controllare 
solJoint = np.load('npy/SJoint_MVG.npy')
solJoint

array([[1.58575943e+000, 1.04243514e+000, 2.72957564e-062,
        2.24806026e-182, 1.41705326e-209, 3.71159641e+000,
        2.73554357e+000, 1.77783391e+000, 1.88494475e-075,
        1.38281331e-073, 6.75473622e-001, 1.25923986e-001,
        3.27963237e-067, 2.60765569e-001, 4.86691243e-246,
        1.59659471e-034, 6.14615463e-184, 5.56896774e-073,
        1.52018824e-001, 1.47475180e-106, 5.73724955e-003,
        2.69557088e-213, 2.93005929e+000, 2.04486323e+000,
        4.46535964e-173, 3.57224919e+000, 6.01202795e-177,
        1.73618815e-061, 1.22661255e-052, 3.04373991e-037,
        5.93105804e-156, 1.88023605e-152, 5.65586443e-100,
        4.20695998e-108, 8.00340945e-001, 1.16366505e-043,
        2.36030153e-176, 1.06685624e-127, 3.61775980e+000,
        5.06643905e-078, 7.20278540e-061, 3.35571731e-106,
        1.18718880e-076, 7.59266808e-002, 1.64162425e+000,
        1.05273322e+000, 1.23817483e-141, 2.02173642e-053,
        1.05499498e-212, 3.09755432e+000],
       [6.086

In [11]:
Spost=getSPost(params,DVAL,1/3)
Spost

array([[1.00000000e+000, 1.00000000e+000, 9.35681540e-062,
        5.75063125e-182, 1.38742252e-207, 1.00000000e+000,
        1.00000000e+000, 1.00000000e+000, 3.66921886e-075,
        3.28548075e-073, 1.00000000e+000, 1.00000000e+000,
        4.73773100e-067, 1.00000000e+000, 3.23377386e-240,
        1.03988553e-033, 1.22693978e-180, 2.68588568e-072,
        1.00000000e+000, 1.07779007e-105, 1.00000000e+000,
        2.84496941e-210, 1.00000000e+000, 1.00000000e+000,
        7.46172719e-172, 1.00000000e+000, 6.68149661e-176,
        9.78087515e-062, 1.04699282e-052, 3.12772907e-036,
        1.58138477e-155, 1.51421514e-151, 3.81388355e-099,
        3.07091067e-107, 1.00000000e+000, 3.61141619e-043,
        7.05320574e-176, 2.21700238e-127, 1.00000000e+000,
        1.26605476e-077, 1.09315585e-060, 9.89183305e-105,
        1.32276686e-075, 1.00000000e+000, 1.00000000e+000,
        1.00000000e+000, 3.27286598e-141, 6.32513224e-052,
        1.49557593e-209, 1.00000000e+000],
       [3.838

In [12]:
predictions=Spost.argmax(axis=0)
predictions

array([0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1, 0, 2, 0, 2,
       0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 2, 1, 0, 1, 2, 2, 0, 1, 1, 2, 1, 0,
       0, 0, 2, 1, 2, 0])

In [13]:
accuracy=np.where(predictions == LVAL,1,0).mean()
err=1-accuracy

print(f"The error rate for MVG is: {err*100}% and the accuracy: {accuracy*100}%")

The error rate for MVG is: 4.0000000000000036% and the accuracy: 96.0%


## Naive Bayes Gaussian Classifier

Consideriamo ora la versione Naive Bayes del classificatore. Come abbiamo visto, la versione Naive Bayes dell'MVG è semplicemente un classificatore Gaussiano dove le matrici di covarianza sono diagonali. La soluzione ML per i parametri della media è la stessa, mentre la soluzione ML per le matrici di covarianza è:

$$\text{diag}(\Sigma_c^*) = \text{diag}\left(\frac{1}{N_c} \sum_i (x_{c,i} - \mu_c^*)(x_{c,i} - \mu_c^*)^T\right)$$

cioè la diagonale della soluzione ML per il modello MVG. Il classificatore Naive Bayes assume che le feature siano condizionatamente indipendenti data la classe, il che semplifica il calcolo della probabilità e spesso migliora la generalizzazione quando il numero di campioni di training è limitato.

In [14]:
DTR.shape

(4, 100)

In [15]:
params=get_params_Naive_Bayes(DTR,LTR)
params

[(array([4.96129032, 3.42903226, 1.46451613, 0.2483871 ]),
  array([[0.13140479, 0.        , 0.        , 0.        ],
         [0.        , 0.16270552, 0.        , 0.        ],
         [0.        , 0.        , 0.03583767, 0.        ],
         [0.        , 0.        , 0.        , 0.0108845 ]])),
 (array([5.91212121, 2.78484848, 4.27272727, 1.33939394]),
  array([[0.26470156, 0.        , 0.        , 0.        ],
         [0.        , 0.10613407, 0.        , 0.        ],
         [0.        , 0.        , 0.21955923, 0.        ],
         [0.        , 0.        , 0.        , 0.03208448]])),
 (array([6.45555556, 2.92777778, 5.41944444, 1.98888889]),
  array([[0.30080247, 0.        , 0.        , 0.        ],
         [0.        , 0.08533951, 0.        , 0.        ],
         [0.        , 0.        , 0.18434414, 0.        ],
         [0.        , 0.        , 0.        , 0.0804321 ]]))]

In [16]:
Spost=getSPost(params,DVAL,1/3)
predictions=Spost.argmax(axis=0)
accuracy=np.where(predictions == LVAL,1,0).mean()
err=1-accuracy

print(f"The error rate for Naive Bayes is: {err*100}% and the accuracy: {accuracy*100}%")

The error rate for Naive Bayes is: 4.0000000000000036% and the accuracy: 96.0%


## Classificatore Gaussiano a Covarianza Legata

Consideriamo ora la versione a covarianza legata (Tied Covariance) del classificatore. In questo caso, le matrici di covarianza delle classi sono legate, con $\Sigma_c = \Sigma$. Abbiamo visto che la soluzione ML per le medie delle classi rimane la stessa. La soluzione ML per la matrice di covarianza è data dalla matrice di covarianza entro-classe empirica:

$$\Sigma^* = \frac{1}{N} \sum_c \sum_i (x_{c,i} - \mu_c^*)(x_{c,i} - \mu_c^*)^T$$

Questo approccio raggruppa le informazioni di covarianza su tutte le classi, il che può migliorare la generalizzazione quando il numero di campioni di training è limitato e riduce il numero di parametri da stimare.

In [18]:
_,Sw=compute_Sb_Sw(DTR,LTR)
Sw

array([[0.23637589, 0.09525344, 0.1364944 , 0.03614529],
       [0.09525344, 0.11618517, 0.05768855, 0.0357726 ],
       [0.1364944 , 0.05768855, 0.14992811, 0.03746458],
       [0.03614529, 0.0357726 , 0.03746458, 0.04291763]])

In [20]:
params_TCG=get_params_Tied_Covariance(DTR,LTR)
params_TCG

[array([4.96129032, 3.42903226, 1.46451613, 0.2483871 ]),
 array([5.91212121, 2.78484848, 4.27272727, 1.33939394]),
 array([6.45555556, 2.92777778, 5.41944444, 1.98888889]),
 array([[0.23637589, 0.09525344, 0.1364944 , 0.03614529],
        [0.09525344, 0.11618517, 0.05768855, 0.0357726 ],
        [0.1364944 , 0.05768855, 0.14992811, 0.03746458],
        [0.03614529, 0.0357726 , 0.03746458, 0.04291763]])]

In [21]:
Spost=getSPost_Tied_Covariance(params_TCG,DVAL,1/3)
predictions=Spost.argmax(axis=0)
accuracy=np.where(predictions == LVAL,1,0).mean()
err=1-accuracy

print(f"The error rate for Tied Covariance Matrix is: {err*100}% and the accuracy: {accuracy*100}%")

The error rate for Tied Covariance Matrix is: 2.0000000000000018% and the accuracy: 98.0%


## Compiti Binari: Rapporti di Verosimiglianza Logaritmica e MVG

Ora ci concentriamo sulla stessa attività binaria che abbiamo utilizzato per LDA (vedi Laboratorio 3), che richiede la classificazione di solo due tipi di fiori, iris versicolor e iris virginica. Puoi fare riferimento al Laboratorio 2 per costruire il dataset a 2 classi.

Sebbene potremmo procedere allo stesso modo utilizzato per il problema iris multiclasse, per i compiti binari abbiamo visto che possiamo rappresentare la classificazione come un confronto di un punteggio, il rapporto di verosimiglianza logaritmica, con una soglia t che dipende dai priori delle classi.

Assumendo che la classe 2 sia la classe vera e la classe 1 sia la classe falsa (cioè, stiamo testando l'ipotesi che un fiore sia della classe virginica), il rapporto di verosimiglianza logaritmica è definito come:

$$s(x_t) = \text{llr}(x_t) = \log \frac{f_{X|C}(x_t|2)}{f_{X|C}(x_t|1)} = \log \frac{\mathcal{N}(x_t|\mu_2, \Sigma_2)}{\mathcal{N}(x_t|\mu_1, \Sigma_1)} = \log \mathcal{N}(x_t|\mu_2, \Sigma_2) - \log \mathcal{N}(x_t|\mu_1, \Sigma_1)$$

In [22]:
DB,LB=init_dataset_for_binary_classification()
(DTR, LTR), (DVAL, LVAL) = split_db_2to1(DB, LB)

In [23]:
params=get_params_MVG(DTR,LTR)
S=getS(params,DVAL)
log_versicolor=S[0,:]
log_virginica=S[1,:]

s=log_virginica-log_versicolor
s

array([-11.56868085,   5.85068743, -11.27235327,   8.21028284,
       -11.01737549, -16.33634695,  -8.67467942,   6.90202853,
        15.21682395,   0.87635727,   1.18539976,  22.67868915,
        13.06138218,   2.08227323, -10.22051843,  -7.65723886,
        -0.57149325,  -8.43768434,  -7.40963963,  17.17228825,
         7.34056812, -12.03802057,   2.31541895,  14.19332118,
         2.37238573,  -7.75569685, -11.28128524,  -1.31763964,
        -4.9011698 ,   7.09557504,   3.69406061,  28.94502635,
        -9.94233154,  -7.10623745])

In [24]:
t=0
predictions_binary_classifier=np.where(s>=0,2,1)
accuracy=np.where(predictions_binary_classifier == LVAL,1,0).mean()
err=1-accuracy

print(f"The error rate for Binary Classifier is: {err*100}% and the accuracy: {accuracy*100}%")

The error rate for Binary Classifier is: 8.823529411764708% and the accuracy: 91.17647058823529%


In [25]:
params_Naive_Bayes=get_params_Naive_Bayes(DTR,LTR)
S_NaiveBayes=getS(params_Naive_Bayes,DVAL)
log_versicolor=S_NaiveBayes[0,:]
log_virginica=S_NaiveBayes[1,:]
s=log_virginica-log_versicolor
predictions_Naive_Bayes=np.where(s>=0,2,1)
accuracy=np.where(predictions_Naive_Bayes == LVAL,1,0).mean()
err=1-accuracy

print(f"The error rate for Binary Classifier based on Naive Bayes is: {err*100}% and the accuracy: {accuracy*100}%")

The error rate for Binary Classifier based on Naive Bayes is: 11.764705882352944% and the accuracy: 88.23529411764706%


In [26]:
params_TCG=get_params_Tied_Covariance(DTR,LTR)
S_TGC=getS_Tied_Covariance(params_TCG,DVAL)
log_versicolor=S_TGC[0,:]
log_virginica=S_TGC[1,:]
s=log_virginica-log_versicolor
predictions_TCG=np.where(s>=0,2,1)
accuracy=np.where(predictions_TCG == LVAL,1,0).mean()
err=1-accuracy

print(f"The error rate for Binary Classifier based on Tied Covariance Matrix is: {err*100}% and the accuracy: {accuracy*100}%")

The error rate for Binary Classifier based on Tied Covariance Matrix is: 5.882352941176472% and the accuracy: 94.11764705882352%
